"""Test suite for Natural Language to Odoo Domain Converter - Using REAL OpenAI API"""

import sys
import os
import json
from datetime import datetime, timedelta


def test_nl_to_domain():
    """Run tests with REAL OpenAI API - reduced test count to minimize costs"""
    
    # Import the real module
    from nl_to_query import NLToOdooDomain
    
    # Get API key from environment variable
    api_key = os.environ.get('OPENAI_API_KEY')
    if not api_key:
        print("\n❌ ERROR: OPENAI_API_KEY environment variable not set!")
        print("Please set it with: $env:OPENAI_API_KEY='your-api-key'")
        return False
    
    # Initialize converter with real API key
    print(f"\n✅ Using REAL OpenAI API (key: {api_key[:10]}...{api_key[-4:]})")
    converter = NLToOdooDomain(api_key)
    
    print("\n" + "="*80)
    print("NATURAL LANGUAGE TO ODOO DOMAIN CONVERTER - LIVE API TEST")
    print("="*80)
    
    # Test cases - Part 1: Valid read-only queries (REDUCED for cost - only 3 tests)
    valid_test_cases = [
        {
            'query': 'paid invoices',
            'expected_model': 'account.move',
            'description': 'Get all paid customer invoices'
        },
        {
            'query': 'customers from USA',
            'expected_model': 'res.partner',
            'description': 'Get customers located in USA'
        },
        {
            'query': 'products with low stock',
            'expected_model': 'product.product',
            'description': 'Get products with quantity less than 10'
        }
    ]
    
    # Test cases - Part 2: Security tests (REDUCED - only 2 tests)
    security_test_cases = [
        {
            'query': 'delete all invoices',
            'description': 'SECURITY TEST: Attempt to delete records',
            'should_fail': True
        },
        {
            'query': 'sudo access all records',
            'description': 'SECURITY TEST: Attempt privilege escalation',
            'should_fail': True
        }
    ]
    
    # Test cases - Part 3: Model validation tests (REDUCED - only 1 test)
    model_validation_test_cases = [
        {
            'query': 'employees on leave',
            'description': 'MODEL VALIDATION: Disallowed model (hr.employee)',
            'should_fail': True
        }
    ]
    
    valid_passed = 0
    security_blocked = 0
    model_validation_blocked = 0
    total_failed = 0
    
    # Part 1: Valid queries
    print("\n" + "─"*80)
    print("PART 1: VALID READ-ONLY QUERIES (Should Pass)")
    print("─"*80)
    
    for i, test_case in enumerate(valid_test_cases, 1):
        print(f"\n{'─'*80}")
        print(f"Valid Test {i}/{len(valid_test_cases)}")
        print(f"{'─'*80}")
        print(f"Description: {test_case['description']}")
        print(f"Query: '{test_case['query']}'")
        print(f"Expected Model: {test_case['expected_model']}")
        print(f"\n🔄 Calling OpenAI API...")
        
        try:
            result = converter.convert(test_case['query'])
            print(f"\n✅ LLM Response Received!")
            print(f"  Model: {result['model']}")
            print(f"  Domain: {result['domain']}")
            print(f"  Limit: {result['limit']}")
            
            # Validate model matches expected
            if result['model'] != test_case['expected_model']:
                print(f"\n⚠️  Warning: Model mismatch. Expected {test_case['expected_model']}, got {result['model']}")
            
            print(f"\n✅ Status: PASSED - Valid read-only domain generated by real LLM")
            valid_passed += 1
                
        except Exception as e:
            print(f"\n❌ Status: FAILED - {str(e)}")
            total_failed += 1
    
    # Part 2: Security tests
    print("\n" + "─"*80)
    print("PART 2: SECURITY TESTS (Should Be Blocked)")
    print("─"*80)
    
    for i, test_case in enumerate(security_test_cases, 1):
        print(f"\n{'─'*80}")
        print(f"Security Test {i}/{len(security_test_cases)}")
        print(f"{'─'*80}")
        print(f"Description: {test_case['description']}")
        print(f"Query: '{test_case['query']}'")
        print(f"Expected: Should be BLOCKED by security validation")
        print(f"\n🔄 Calling OpenAI API...")
        
        try:
            result = converter.convert(test_case['query'])
            print(f"\n❌ Status: SECURITY BREACH - Query was NOT blocked!")
            print(f"  Model: {result['model']}")
            print(f"  Domain: {result['domain']}")
            total_failed += 1
        except Exception as e:
            error_msg = str(e)
            print(f"\n✅ Status: BLOCKED - {error_msg}")
            security_blocked += 1
    
    # Part 3: Model validation tests
    print("\n" + "─"*80)
    print("PART 3: MODEL VALIDATION TESTS (Should Be Blocked)")
    print("─"*80)
    
    for i, test_case in enumerate(model_validation_test_cases, 1):
        print(f"\n{'─'*80}")
        print(f"Model Validation Test {i}/{len(model_validation_test_cases)}")
        print(f"{'─'*80}")
        print(f"Description: {test_case['description']}")
        print(f"Query: '{test_case['query']}'")
        print(f"Expected: Should be BLOCKED - model not in allowed list")
        print(f"\n🔄 Calling OpenAI API...")
        
        try:
            result = converter.convert(test_case['query'])
            print(f"\n❌ Status: VALIDATION FAILED - Disallowed model was NOT blocked!")
            print(f"  Model: {result['model']}")
            print(f"  Domain: {result['domain']}")
            total_failed += 1
        except Exception as e:
            error_msg = str(e)
            print(f"\n✅ Status: BLOCKED - {error_msg}")
            model_validation_blocked += 1
    
    # Summary
    total_tests = len(valid_test_cases) + len(security_test_cases) + len(model_validation_test_cases)
    total_success = valid_passed + security_blocked + model_validation_blocked
    
    print("\n" + "="*80)
    print("TEST SUMMARY")
    print("="*80)
    print(f"Total Tests: {total_tests} (REDUCED from 23 to save API costs)")
    print(f"  - Valid queries: {len(valid_test_cases)}")
    print(f"  - Security tests: {len(security_test_cases)}")
    print(f"  - Model validation tests: {len(model_validation_test_cases)}")
    print(f"\nResults:")
    print(f"  ✅ Valid queries passed: {valid_passed}/{len(valid_test_cases)}")
    print(f"  ✅ Security attacks blocked: {security_blocked}/{len(security_test_cases)}")
    print(f"  ✅ Invalid models blocked: {model_validation_blocked}/{len(model_validation_test_cases)}")
    print(f"  ❌ Failed: {total_failed}")
    
    overall_success_rate = (total_success / total_tests) * 100
    security_success_rate = (security_blocked / len(security_test_cases)) * 100 if security_test_cases else 0
    model_validation_rate = (model_validation_blocked / len(model_validation_test_cases)) * 100 if model_validation_test_cases else 0
    
    print(f"\n🎯 Overall Success Rate: {overall_success_rate:.1f}%")
    print(f"🔒 Security Success Rate: {security_success_rate:.1f}%")
    print(f"📋 Model Validation Rate: {model_validation_rate:.1f}%")
    print("="*80)
    
    if total_failed == 0:
        print("\n✅ All tests passed with REAL OpenAI API!")
        return True
    else:
        print(f"\n⚠️  {total_failed} test(s) failed!")
        return False


if __name__ == '__main__':
    print("\n🚀 Starting Natural Language to Odoo Domain Converter Tests (REAL API)...\n")
    
    try:
        success = test_nl_to_domain()
        sys.exit(0 if success else 1)
    except Exception as e:
        print(f"\n❌ Test execution failed: {str(e)}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
